POST http://localhost:3002/api/v1/change-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJpYmhlc3RlZUBnbWFpbC5jb20iLCJpYXQiOjE2ODg1OTg2NzcsImV4cCI6MTY4ODY1MjY3N30.avT7MZD8MbF1hNwaHfQI5VMVg16kBV0JpVm0gI31K94

{
    "email": "bibhestee@gmail.com",
    "password": "Password22@",
    "newPassword": "password",
    "securityQuestion": "ilorin"
}

### Correct Request

POST http://localhost:3002/api/v1/change-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJpYmhlc3RlZUBnbWFpbC5jb20iLCJpYXQiOjE2ODg1OTg2NzcsImV4cCI6MTY4ODY1MjY3N30.avT7MZD8MbF1hNwaHfQI5VMVg16kBV0JpVm0gI31K94

{
    "email": "bibhestee@gmail.com",
    "password": "Password22@",
    "newPassword": "Password@22",
    "securityQuestion": "ilorin"
}


### Correct Request

POST http://localhost:3002/api/v1/change-password HTTP/1.1
Content-Type: application/json
Authorization: 

{
    "newPassword": "Johndoeengnr2",
    "email": "johndoe@gmail.com",
    "password": "johndoeengineer",
    "securityQuestion": "ilorin"
}

### Incorrect security question

POST http://localhost:3002/api/v1/change-password HTTP/1.1
Content-Type: application/json
Authorization: 

{
    "email": "bibhestee@gmail.com",
    "password": "Password22@",
    "newPassword": "password",
    "securityQuestion": "ibadan"
}


### Missing security question

POST http://localhost:3002/api/v1/change-password HTTP/1.1
Content-Type: application/json
Authorization: 

{
    "email": "bibhestee@gmail.com",
    "password": "Password22@",
    "newPassword": "password"
}

### Missing password

POST http://localhost:3002/api/v1/change-password HTTP/1.1
Content-Type: application/json
Authorization: 

{
    "email": "bibhestee@gmail.com",
    "newPassword": "password",
    "securityQuestion": "ilorin"
}

### Missing new password

POST http://localhost:3002/api/v1/change-password HTTP/1.1
Content-Type: application/json
Authorization: 

{
    "email": "bibhestee@gmail.com",
    "password": "password",
    "securityQuestion": "ilorin"
}

### Missing email

POST http://localhost:3002/api/v1/change-password HTTP/1.1
Content-Type: application/json
Authorization: 

{
    "password": "password",
    "newPassword": "password",
    "securityQuestion": "ilorin"
}

### Incorrect route

POST http://localhost:3002/api/v1/changepassword HTTP/1.1
Content-Type: application/json
Authorization: 

{
    "email": "bibhestee@gmail.com",
    "password": "password",
    "newPassword": "password",
    "securityQuestion": "ilorin"
}