POST http://localhost:3002/api/v1/change-password HTTP/1.1
Content-Type: application/json

{
    "email": "bibhestee@gmail.com",
    "password": "Password22@",
    "newPassword": "password",
    "securityQuestion": "ilorin"
}

### Wrong password

POST http://localhost:3002/api/v1/change-password HTTP/1.1
Content-Type: application/json

{
    "email": "bibhestee@gmail.com",
    "password": "password",
    "newPassword": "password",
    "securityQuestion": "ilorin"
}

### Incorrect security question

POST http://localhost:3002/api/v1/change-password HTTP/1.1
Content-Type: application/json

{
    "email": "bibhestee@gmail.com",
    "password": "Password22@",
    "newPassword": "password",
    "securityQuestion": "ibadan"
}


### Missing security question

POST http://localhost:3002/api/v1/change-password HTTP/1.1
Content-Type: application/json

{
    "email": "bibhestee@gmail.com",
    "password": "Password22@",
    "newPassword": "password"
}

### Missing password

POST http://localhost:3002/api/v1/change-password HTTP/1.1
Content-Type: application/json

{
    "email": "bibhestee@gmail.com",
    "newPassword": "password",
    "securityQuestion": "ilorin"
}

### Missing new password

POST http://localhost:3002/api/v1/change-password HTTP/1.1
Content-Type: application/json

{
    "email": "bibhestee@gmail.com",
    "password": "password",
    "securityQuestion": "ilorin"
}

### Missing email

POST http://localhost:3002/api/v1/change-password HTTP/1.1
Content-Type: application/json

{
    "password": "password",
    "newPassword": "password",
    "securityQuestion": "ilorin"
}

### Incorrect route

POST http://localhost:3002/api/v1/changepassword HTTP/1.1
Content-Type: application/json

{
    "email": "bibhestee@gmail.com",
    "password": "password",
    "newPassword": "password",
    "securityQuestion": "ilorin"
}