POST http://localhost:3002/api/v1/forget-password HTTP/1.1
Content-Type: application/json

{
    "email": "bibhestee@gmail.com",
    "newPassword": "Password22@",
    "confirmPassword": "Password22@",
    "securityQuestion": "ilorin"
}

### Unmatch new password and confirm password

POST http://localhost:3002/api/v1/forget-password HTTP/1.1
Content-Type: application/json

{
    "email": "bibhestee@gmail.com",
    "newPassword": "newpassword",
    "confirmPassword": "password",
    "securityQuestion": "ilorin"
}

### Missing security question

POST http://localhost:3002/api/v1/forget-password HTTP/1.1
Content-Type: application/json

{
    "email": "bibhestee@gmail.com",
    "newPassword": "newpassword",
    "confirmPassword": "newpassword"
}

### Missing password

POST http://localhost:3002/api/v1/forget-password HTTP/1.1
Content-Type: application/json

{
    "email": "bibhestee@gmail.com",
    "confirmPassword": "newpassword",
    "securityQuestion": "ilorin"
}

### Missing confirm password

POST http://localhost:3002/api/v1/forget-password HTTP/1.1
Content-Type: application/json

{
    "email": "bibhestee@gmail.com",
    "newPassword": "newpassword",
    "securityQuestion": "ilorin"
}

### Missing email

POST http://localhost:3002/api/v1/forget-password HTTP/1.1
Content-Type: application/json

{
    "newPassword": "newpassword",
    "confirmPassword": "newpassword",
    "securityQuestion": "ilorin"
}

### Incorrect route

POST http://localhost:3002/api/v1/forgetpassword HTTP/1.1
Content-Type: application/json

{
    "email": "bibhestee@gmail.com",
    "newPassword": "newpassword",
    "confirmPassword": "newpassword",
    "securityQuestion": "ilorin"
}