POST http://localhost:3002/api/v1/forget-password HTTP/1.1
Content-Type: application/json

{
    "email": "bibhestee@gmail.com",
    "newPassword": "newpassword",
    "confirmPassword": "newpassword",
    "securityQuestion": "ilorin"
}
